random_forest:
    criterion: 'gini'
    max_features: 'sqrt'
    min_samples_split: 10
    min_samples_leaf: 4
    n_estimators: 50
    max_depth: null
    random_state: 42
    class_weight: 'balanced'
    n_jobs: -1 