random_forest:
    criterion: 'entropy'
    max_features: 'sqrt'
    min_samples_split: 2
    min_samples_leaf: 1
    n_estimators: 50
    max_depth: null
    random_state: 42
    class_weight: 'balanced'
    n_jobs: -1 

logistic_regression:
    penalty: 'l2'
    C: 1.0
    solver: 'lbfgs'
    max_iter: 200
    random_state: 42
    class_weight: 'balanced'
    n_jobs: -1

