random_forest:
    criterion: 'gini'
    max_features: 'sqrt'
    min_samples_split: 2
    min_samples_leaf: 1
    n_estimators: 300
    max_depth: 3
    random_state: 42
    class_weight: 'balanced'
    n_jobs: -1 