COLUMNS:
  transactionid: int64
  customerid: int64
  transactiondate: object
  transactiontype: object
  amount: float64
  productcategory: object
  productsubcategory: object
  branchcity: object
  branchlat: float64
  branchlong: float64
  channel: object
  currency: object
  creditcardfees: float64
  insurancefees: float64
  latepaymentamount: float64
  customerscore: int64
  monthlyincome: float64
  customersegment: object
  recommendedoffer: object

target_column:
  name: recommendedoffer

