COLUMNS:
  TransactionID: int64
  CustomerID: int64
  TransactionDate: datetime64[ns]
  TransactionType: str
  Amount: float64
  ProductCategory: str
  ProductSubcategory: str
  BranchCity: str
  BranchLat: float64
  BranchLong: float64
  Channel: str
  Currency: str
  CreditCardFees: float64
  InsuranceFees: float64
  LatePaymentAmount: float64
  CustomerScore: int64
  MonthlyIncome: float64
  CustomerSegment: str
  RecommendedOffer: str

target_column:
  name: RecommendedOffer
