artifacts_root: artifacts

# Configuration for data generation process
data_generation:
  num_customers: 7000
  gen_root_dir: artifacts/data_generation
  data_dir: artifacts/data_generation/raw_data
  output_dir: artifacts/data_generation
  db_file: artifacts/data_generation/bank_products_recommender.db
  customers_filename: bank_customers.csv
  products_filename: product_catalog.csv
  table:
    customers: customers
    products: products


# Configuration for data ingestion process
data_ingestion:
  root_dir: artifacts/data_ingestion
  raw_data_dir: artifacts/data_ingestion/raw_data
  data_file: artifacts/data_generation/bank_products_recommender.db
  customers_csv: artifacts/data_ingestion/raw_data/bank_customers.csv
  products_csv: artifacts/data_ingestion/raw_data/product_catalog.csv

# Configuration for data validation process
data_validation:
  root_dir: artifacts/data_validation
  data_dir: artifacts/data_validation
  schema_file: config/schema.yaml
 
# Configuration for data transformation process
data_transformation:
  root_dir: artifacts/data_transformation
  joined_data_file: artifacts/data_transformation/joined_data.csv
  transformed_data_file: artifacts/data_transformation/transformed_data.csv
  customer_path: artifacts/data_ingestion/raw_data/bank_customers.csv
  product_path: artifacts/data_ingestion/raw_data/product_catalog.csv
  train_data_file : artifacts/data_transformation/train_data.csv
  test_data_file : artifacts/data_transformation/test_data.csv

# Configuration for model training process
model_training:
  root_dir: artifacts/model_training
  train_data_dir: artifacts/data_transformation/train_data.csv
  test_data_dir: artifacts/data_transformation/test_data.csv
  model_name: model.joblib
  
  

# Configuration for model evaluation process
model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test_data.csv
  model_path: artifacts/model_training/model.joblib
  grid_search_model_path: artifacts/model_training/grid_search_model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json

#  Feature Importance
feature_importance:
  root_dir: artifacts/feature_importance
  model_path: artifacts/model_training/model.joblib
  grid_search_model: artifacts/model_training/grid_search_model.joblib
  training_data_path: artifacts/data_transformation/train_data.csv
  test_data_path: artifacts/data_transformation/test_data.csv
  feature_importance_file: artifacts/feature_importance/feature_importance.json 


