artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  raw_data_dir: artifacts/data_ingestion/raw_data
  customers_csv: artifacts/data_ingestion/raw_data/bank_customers.csv
  products_csv: artifacts/data_ingestion/raw_data/product_catalog.csv

database:
  root_dir: artifacts/database
  db_file: artifacts/database/bank_recommender.db
  tables:
    customers: customers
    products: products

