artifacts_root: artifacts

# Configuration for data ingestion process
data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_file: "https://github.com/richardmukechiwa/Datasets/raw/refs/heads/main/Banking_Dataset.csv"
  #export_csv_path: artifacts/data_ingestion/customer_data.csv
  output_path:  artifacts/data_ingestion/customer_data.csv
  table_name: bank_transactions


# Configuration for data validation process
data_validation:
  val_root_dir: artifacts/data_validation
  customer_data: artifacts/data_ingestion/customer_data.csv
  STATUS_FILE: artifacts/data_validation/status.txt

 
# Configuration for data transformation process
data_transformation:
  root_dir: artifacts/data_transformation
  customer_path: artifacts/data_ingestion/customer_data.csv
  transformed_data_file: artifacts/data_ingestion/transform_data.csv
  train_data_file : artifacts/data_transformation/train_data.csv
  test_data_file : artifacts/data_transformation/test_data.csv
  

# Configuration for model training process
model_training:
  root_dir: artifacts/model_training
  train_data_dir: artifacts/data_transformation/train_data.csv
  test_data_dir: artifacts/data_transformation/test_data.csv
  model_name: random.joblib
  label_encoder_file: label_encoder.joblib
  
  

# Configuration for model evaluation process
model_evaluation:
  root_dir: artifacts/model_evaluation
  train_data_path: artifacts/data_transformation/train_data.csv
  test_data_path: artifacts/data_transformation/test_data.csv
  model_path: artifacts/model_training/random.joblib
  grid_search_model_path: artifacts/model_training/grid_search_model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json
  encoded_target_label: artifacts/model_training/label_encoder.joblib

#  Feature Importance
feature_importance:
  root_dir: artifacts/feature_importance
  model_path: artifacts/model_training/model.joblib
  grid_search_model: artifacts/model_training/grid_search_model.joblib
  training_data_path: artifacts/data_transformation/train_data.csv
  test_data_path: artifacts/data_transformation/test_data.csv
  feature_importance_file: artifacts/feature_importance/feature_importance.json 


