artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_urls:
    bank_customers: https://github.com/richardmukechiwa/Datasets/raw/refs/heads/main/bank_customers.zip
    product_catalog: https://github.com/richardmukechiwa/Datasets/raw/refs/heads/main/product_catalog.zip
  local_data_file: artifacts/data_ingestion/raw_data.zip
  unzip_dir: artifacts/data_ingestion

